In [3]:
import numpy
numpy.__version__

'2.1.3'

In [4]:
import numpy as np;
np.__version__

'2.1.3'

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[0] = 100
L

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10).dtype

dtype('float64')

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.full((3,6), 44, dtype=int)

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [12]:
[i for i in range(3, 10, 2)]

[3, 5, 7, 9]

In [13]:
np.random.randint(0, 10, (3, 4))

array([[6, 4, 4, 5],
       [3, 6, 8, 4],
       [8, 0, 9, 7]])

In [14]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [15]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [16]:
X = np.arange(10).reshape((2, 5))
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.ndim

1

In [19]:
X.ndim

2

In [21]:
x[0:5]

array([0, 1, 2, 3, 4])

In [22]:
x[: : 2]

array([0, 2, 4, 6, 8])

In [27]:
X[:1, :3]

array([[0, 1, 2]])

In [28]:
X[::-1, ::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [31]:
X[:,0]

array([0, 5])

In [32]:
subX= X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [36]:
X[0, 0] = 1

In [37]:
subX

array([[1, 1, 2],
       [5, 6, 7]])

In [38]:
secX = X[:2, :3].copy()
secX

array([[1, 1, 2],
       [5, 6, 7]])

In [39]:
secX[0, 0] = 100
secX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
X

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
x.shape

(10,)

In [42]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
B = np.array([1,2,3])
C = np.array([4,5,6])
D = np.array([7,8,9])
np.concatenate([B, C, D])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
E = np.array([[1,2,3], [4,5,666]])
np.concatenate([E, B.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5, 666],
       [  1,   2,   3]])

In [54]:
F = np.vstack([E, B])
F

array([[  1,   2,   3],
       [  4,   5, 666],
       [  1,   2,   3]])

In [56]:
G = np.full([3, 3], 100)
np.hstack([F, G])

array([[  1,   2,   3, 100, 100, 100],
       [  4,   5, 666, 100, 100, 100],
       [  1,   2,   3, 100, 100, 100]])

In [57]:
H = np.arange(10)
x1, x2, x3 = np.split(H, [3, 7])
x1, x2, x3

(array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9]))

In [60]:
H = np.arange(10)
x1, x2= np.split(H, [2])
x1, x2

(array([0, 1]), array([2, 3, 4, 5, 6, 7, 8, 9]))

In [63]:
I = np.arange(16).reshape([4,4])
lower, upper = np.vsplit(I, [2])
lower, upper

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [65]:
I = np.arange(16).reshape([4,4])
left, right = np.hsplit(I, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [ ]:
J = np.arange(16).reshape([4,4])
X, y = np.hsplit(J, [3])
y[:, -1]

array([ 3,  7, 11, 15])

In [70]:
n=10
A=[i for i in range(n)]
list = []
for e in A:
  list.append(e*2)
list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [80]:
A = np.array([i for i in range(16)])
B = A.reshape(4,4)
B*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [82]:
A = np.arange(4).reshape(2, 2)
B = np.full((2,2), 20)
A+B, A*B

(array([[20, 21],
        [22, 23]]),
 array([[ 0, 20],
        [40, 60]]))

In [83]:
A.T

array([[0, 2],
       [1, 3]])

In [85]:
B = np.array([1,2,3,4]);
np.vstack([B]*A.shape[0])


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [91]:
A
np.linalg.inv(A)     ### 求逆运算

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [94]:
pinvX = np.linalg.pinv(A)  ### 求伪逆运算
pinvX.shape

(2, 2)

In [ ]:
L = np.random.random(100)
np.sum(L)
np.min(L)
np.max(L)

np.float64(0.9955908359841159)

In [101]:
L = np.arange(16).reshape(4, -1)
np.sum(L)

np.int64(120)

In [102]:
np.sum(L, axis=0)

array([24, 28, 32, 36])

In [103]:
np.prod(L)

np.int64(0)

In [34]:
import numpy as np;
x = np.random.normal(0, 1, size=1000)
np.min(x)
np.argmin(x)

np.int64(954)

In [36]:
x = np.arange(16)
np.random.shuffle(x)
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
x = np.random.randint(10, size = (4, 4))
np.sort(x, axis=1)

array([[3, 6, 6, 7],
       [0, 1, 3, 5],
       [2, 4, 4, 7],
       [5, 5, 7, 7]])

In [69]:
X = np.arange(16)
np.random.shuffle(X)
# np.argsort(X)

In [70]:
np.partition(X, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
np.argsort(x, axis=1)

array([[3, 1, 2, 0],
       [2, 0, 3, 1],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.argpartition(x, 3, axis=1)