In [3]:
import numpy
numpy.__version__

'2.1.3'

In [4]:
import numpy as np;
np.__version__

'2.1.3'

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[0] = 100
L

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10).dtype

dtype('float64')

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.full((3,6), 44, dtype=int)

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [12]:
[i for i in range(3, 10, 2)]

[3, 5, 7, 9]

In [13]:
np.random.randint(0, 10, (3, 4))

array([[6, 4, 4, 5],
       [3, 6, 8, 4],
       [8, 0, 9, 7]])

In [14]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [15]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [16]:
X = np.arange(10).reshape((2, 5))
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.ndim

1

In [19]:
X.ndim

2

In [21]:
x[0:5]

array([0, 1, 2, 3, 4])

In [22]:
x[: : 2]

array([0, 2, 4, 6, 8])

In [27]:
X[:1, :3]

array([[0, 1, 2]])

In [28]:
X[::-1, ::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [ ]:
X[:,0]

array([], shape=(2, 0), dtype=int64)