In [4]:
import numpy
numpy.__version__

'2.1.3'

In [5]:
import numpy as np;
np.__version__

'2.1.3'

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[0] = 100
L

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10).dtype

dtype('float64')

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.full((3,6), 44, dtype=int)

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [15]:
[i for i in range(3, 10, 2)]

[3, 5, 7, 9]

In [16]:
np.random.randint(0, 10, (3, 4))

array([[4, 3, 9, 7],
       [0, 7, 2, 3],
       [3, 2, 8, 0]])

In [17]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [18]:
np.random.seed(222)
np.random.randint(0, 10, (3, 4))

array([[6, 3, 2, 5],
       [6, 8, 8, 4],
       [7, 8, 8, 0]])

In [20]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/Users/wangjiawei/anaconda3/lib/python3.13/site-packages/numpy/random/__init__.py'>
File:        ~/anaconda3/lib/python3.13/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to ini